export default {
	PATH_BASE: './',
	PATH_SOURCE: 'src/',
	PATH_DEVELOPMENT: 'dev/',
	PATH_TEST: 'test/',
	PATH_PRODUCTION: 'prod/',
	FOLDER_ADMIN: 'admin/',
	FOLDER_API: 'api/',
	FOLDER_WEB: 'web/',
	FOLDER_CONFIG: 'config/',
	FOLDER_UPLOADS: 'uploads/',
	FOLDER_LOGS: 'logs/',
	FOLDER_STATIC: 'static/',
	FOLDER_VENDOR: 'vendor/',
	FOLDER_STYLES_INPUT: 'styles/scss/',
	FOLDER_STYLES_OUTPUT: 'styles/css/',
	FOLDER_STYLES_IMAGES: 'styles/img/',
	FOLDER_SCRIPTS: 'scripts/',
	FOLDER_FONTS: 'styles/fonts/',
	FOLDER_LIBS: 'libs/',
	SCRIPTS_INPUT_FILE: 'index.js',
	STYLES_INPUT_FILE: 'index.scss',
	ENV_INPUT_FILE: '.envfile',
	ENV_OUTPUT_FILE: 'env.php',
	ENV_NAME_DEV: 'development',
	ENV_NAME_TEST: 'test',
	ENV_NAME_PROD: 'production',
	KEY_ENV_ENV: '%%%%%ENV_ENV%%%%%',
	KEY_ENV_TIMESTAMP: '%%%%%ENV_TIMESTAMP%%%%%',

	CLEAN_WITH_UPLOADS: false,
	CLEAN_WITH_LOGS: false,
	ADMIN_EXTERNAL_CSS: true,
	WEB_EXTERNAL_CSS: true,
};
